package com.canopycreations.mysticcraft.listeners;

import com.canopycreations.mysticcraft.MysticCraft;
import com.canopycreations.mysticcraft.lore.Progenitor;
import com.canopycreations.mysticcraft.util.Fx;
import com.canopycreations.mysticcraft.world.Landmark;
import org.bukkit.Bukkit;
import org.bukkit.Color;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.Sound;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.entity.EntityDamageByEntityEvent;

/**
 * The White Oak.
 *
 * This is the single most consequential object in the world, and it is a
 * tree anyone can walk up to with an axe. Felling it:
 *
 *   1. Strips The Original Witch of her progenitor status, permanently.
 *   2. Yields White Oak Stakes - the only wood that kills a vampire for good.
 *   3. Announces itself to every player on the server.
 *
 * That makes the tree a permanent political problem. Vampires want it gone.
 * The Original Witch cannot afford to lose it. Humans want stakes. Nobody
 * can guard it forever. Every one of those tensions is generated by a single
 * block that anyone can break.
 */
public class WhiteOakListener implements Listener {

    private final MysticCraft plugin;

    public WhiteOakListener(MysticCraft plugin) {
        this.plugin = plugin;
    }

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBreak(BlockBreakEvent event) {
        if (event.getBlock().getType() != Material.PALE_OAK_LOG) return;

        Location oak = plugin.getLandmarkManager().getLocation(Landmark.THE_WHITE_OAK);
        if (oak == null) return;
        if (!event.getBlock().getWorld().equals(oak.getWorld())) return;
        if (event.getBlock().getLocation().distance(oak) > 20) return;

        Player player = event.getPlayer();

        // Vampires physically cannot bring themselves to touch it.
        if (plugin.getRaceManager().getRace(player) == com.canopycreations.mysticcraft.races.Race.VAMPIRE) {
            event.setCancelled(true);
            player.sendActionBar("§fYour hands won't do it. Something older than you says no.");
            player.playSound(player.getLocation(), Sound.ENTITY_ENDERMAN_TELEPORT, 0.7f, 0.6f);
            return;
        }

        int remaining = countRemainingLogs(oak);

        // Each log yields a stake - the wood itself is the prize.
        event.setDropItems(false);
        player.getInventory().addItem(plugin.getMysticItems().whiteOakStake());
        Fx.discovery(player);

        if (remaining > 1) {
            player.sendActionBar("§f" + (remaining - 1) + " of the White Oak still stands.");
            oak.getWorld().playSound(oak, Sound.BLOCK_WOOD_BREAK, 2.0f, 0.5f);

            // Everyone nearby knows what's happening.
            for (Player near : oak.getWorld().getPlayers()) {
                if (near.getLocation().distance(oak) < 80 && !near.equals(player)) {
                    near.sendActionBar("§8Someone is cutting at the White Oak.");
                }
            }
            return;
        }

        fellTheOak(player, oak);
    }

    private int countRemainingLogs(Location oak) {
        int count = 0;
        for (int x = -3; x <= 3; x++) {
            for (int y = 0; y < 26; y++) {
                for (int z = -3; z <= 3; z++) {
                    if (oak.clone().add(x, y, z).getBlock().getType() == Material.PALE_OAK_LOG) count++;
                }
            }
        }
        return count;
    }

    private void fellTheOak(Player player, Location oak) {
        // Spectacle: this should feel like a world event, because it is one.
        oak.getWorld().playSound(oak, Sound.ENTITY_ENDER_DRAGON_GROWL, 1.0f, 0.4f);
        oak.getWorld().spawnParticle(org.bukkit.Particle.EXPLOSION, oak.clone().add(0, 10, 0), 8, 3, 6, 3, 0);
        Fx.totemPlanted(oak, Color.fromRGB(240, 240, 230));

        Bukkit.broadcastMessage("");
        Bukkit.broadcastMessage("§8§m                                                        ");
        Bukkit.broadcastMessage("§f§lThe White Oak has fallen.");
        Bukkit.broadcastMessage("§7Felled by §f" + player.getName() + "§7.");
        Bukkit.broadcastMessage("");
        Bukkit.broadcastMessage("§8A thousand years of borrowed permanence, called in at once.");
        Bukkit.broadcastMessage("§8§m                                                        ");
        Bukkit.broadcastMessage("");

        for (Player online : Bukkit.getOnlinePlayers()) {
            online.playSound(online.getLocation(), Sound.ENTITY_ENDER_DRAGON_GROWL, 0.8f, 0.4f);
        }

        // The Original Witch's power was bound to this tree.
        if (plugin.getProgenitorManager().isClaimed(Progenitor.THE_ORIGINAL_WITCH)) {
            plugin.getProgenitorManager().strip(Progenitor.THE_ORIGINAL_WITCH,
                    "§8The tree her power was bound to no longer stands.");
        }

        plugin.getCodexManager().discover(player,
                com.canopycreations.mysticcraft.lore.LoreFragment.THE_ASH_MOTHER);
    }

    /**
     * A White Oak Stake kills any vampire permanently - including one who
     * would normally survive being staked. This is the counter to The
     * Immortal, and the reason the tree matters.
     */
    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onStakeStrike(EntityDamageByEntityEvent event) {
        if (!(event.getEntity() instanceof Player victim)) return;
        if (!(event.getDamager() instanceof Player attacker)) return;

        var weapon = attacker.getInventory().getItemInMainHand();
        if (!plugin.getMysticItems().isWhiteOakStake(weapon)) return;
        if (plugin.getRaceManager().getRace(victim) != com.canopycreations.mysticcraft.races.Race.VAMPIRE) return;

        event.setCancelled(true);
        victim.setHealth(0);

        Progenitor held = plugin.getProgenitorManager().getProgenitorOf(victim.getUniqueId());
        if (held == Progenitor.THE_IMMORTAL) {
            plugin.getProgenitorManager().strip(Progenitor.THE_IMMORTAL,
                    "§8White oak. The one thing that was always going to work.");
            Bukkit.broadcastMessage("§e§lThe Immortal has been killed with white oak.");
            Bukkit.broadcastMessage("§8Two thousand years, ended by a piece of wood.");
        } else {
            Bukkit.broadcastMessage("§f" + attacker.getName() + " §7has staked "
                    + victim.getName() + " §7with white oak. That one doesn't come back.");
        }

        // Consume the stake - the supply is genuinely finite.
        weapon.setAmount(weapon.getAmount() - 1);
        victim.getWorld().playSound(victim.getLocation(), Sound.ITEM_TOTEM_USE, 1.0f, 0.5f);
    }
}
